
POST http://localhost:3500/auth/register
content-type: application/json

{ 
    "email":"ali@yahoo.com",
    "password":"1234"
}
###################
POST http://localhost:3500/auth/login
content-type: application/json

{ 
    "email":"ali@yahoo.com",
    "password":"1234"
}
###################
http://localhost:3500/auth/refresh

###################
http://localhost:3500/auth/logout

############################################################################

http://localhost:3500/products?page=1&limit=20
###
http://localhost:3500/products/index-page
###
http://localhost:3500/products/filtered?page=1&limit=20&kinds=all
###
http://localhost:3500/products/ids
###
http://localhost:3500/products/product/10
###
http://localhost:3500/products/cart?ids=[{"product_id": 9, "inventory_id": 52},{"product_id": 10, "inventory_id": 54}]